# This is a basic workflow to help you get started with Actions

name: Spring Boot CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-18.04

    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :youtugo-application:clean :youtugo-application:build

      - name: Make Directory for deliver
        run: mkdir -p code-deploy-youtugo-application

      - name: Copy Jar
        run: cp youtugo-application/build/libs/*.jar code-deploy-youtugo-application/

      - name: Copy appspec
        run: cp appspec.yml code-deploy-youtugo-application

      - name: Make zip file
        run: zip -r -j code-deploy-youtugo-application.zip code-deploy-youtugo-application/*

      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          code-deploy-youtugo-application.zip s3://az-deploy/

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name az-deploy \
          --deployment-group-name az-deploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=az-deploy,bundleType=zip,key=code-deploy-youtugo-application.zip \
          --region ap-northeast-2




